* History of Mathematics

* Themes which influenced mathematics

- Hydrodynamics on function theory
- Kantianism and surveying on geometry
- Electromagnetism on differential equations
- Cartesianism on mechanics
- Scholasticism on calculus

* Prehistory
Some where in prehistory, counting began by mapping a set of things to objects. Counting with fingers enabled counting with a base that is with respect to an certain radix. Having 10 fingers means that you can now refer to 2 tens or 7 tens by abstracting out the base. This also forms a basis for arithmetic where you can say 14 is 10 + 4 or 114 is 100 * 1 + 10 * 1 + 1 * 4.

A Concise History of Mathematics by Dirk Struik says that calculi (pebbles/pointers) where first used and then came in a base with index that is fingers acting as a reference base.

Our body parts are in many ways the measure of things out there in the world.

* Babylonia

* Egypt

** Rhind Papyrus

** Moscow Papyrus

* Kassites, Assyrians, Medes, Persians

* Sulbasutras

* Greece
Minoan, Mycenean, Hittie worlds dissapeared.
Hebrews, Assyrians, Phoenicians, and the Greeks

Corinth, Athens, Croton, Tarentum

Ionian Rationalism

* Thales of Miletus

Thales symbolizes the foundation of modern mathematics, science, and technology.

* Pythagoras

* Pherecydes

* [Historian] Diogenes Laertius

* Euclid

* Ptolemies

* Diophantus

* Apollonius

* Eratosthenes of Cyrene

* Aristarchus of Samos

* Archimedes

* Hippocrates of Chios

Lunulae
Quadrature of a circle

Apogoge: Word for logical deduction

Stoicheia

Arithmoi

Numbers were divided into Pentagonal, Square, Triangular, Friendly, Perfect, Prime, Composite, Odd, Even, Even times even, Odd times odd

The finding of irrational numbers was found not by extending the concept of numbers but by finding the synthesis is geometry.

* Three central problems in Greek Mathematics

Trisection of angle
Duplication of the Cube / Delian problem
Quadrature of the circle

None of these problems can be solved by the construction of a finite number of straight lines and circles except by approximation. These problems helped open up new fields of mathematics.

Search for the geometrical proportion
Search for the double geometrical proportion

This search led to the discovery of the conics, cubic and quartic curves and the quadratrix

** Leucippus
** Democritus

** Archytas of Tarentum

** Hippocrates of Cos

* Hipparchus

* Zeno
** Paradoxes

- Achilles
- Arrow
- Dichotomy
- Stadium

Potential and actual infinity question

Peloponnesian War (404 B.C.)
Fall of Athens

* Plato
Plato’s Academy

* Archytas
* Theaetetus (d 369 B.C.)
* Eudoxus (408 – 355 B.C.)

Axiom of Eudoxus/Archimedes

** Exhaustion Method
Coined by Grégoire de Saint-Vincent, 1647

“The Method” -> Democritus’ School -> Atom Method

334 B.C. Alexander the Great’s conquest of Persia

Egypt - Ptolemies
Mesopotamia and Syria - Seleucids
Macedonia - Antigonus and his successors

The period of Hellenism

* Euclid (306 - 283 B.C.)

Stoicheia (translated as Data / Elements)

Applications of algebra to geometry but presented in strictly geometrical language

Based on a strict logic deduction of theorems from definitions, postulates, and axioms

First four books: Plane geometry
Fifth book: Eudoxus’ theory of propertions
6th book: Pythagoras and the golden section
7th to 9th book: Number Theory
10th book: Resumes geometrical discussions.
Considered most difficult.
Discusses numbers of the form a+- sqrt(b) and sqrt(a +- sqrt(b))

Last three books: Solid geometry

Attempts to reduce Euclid’s parallel axiom to a theorem has led in the 19th century to the discovery of non-Euclidean geometries
Similarly with axiom of Archimedes and non-Archimedean geometry

First usage of the sign π by William Jones (1706)

Went mainstream with the adoption of Euler in his Introductio.

** Archimedes (287 - 212 B.C.)

** Appollonius of Perga (274 – 205 B.C.)

*** Tangency problem

The conics were known in a different epistemological viewpoint.

Parabola: Application
Ellipse: Application with deficiency
Hyperbola: Application with excess

History of mathematics is intertwined with astronomy

Planetory theory of Eudoxus

* Aristarchus of Samos (c. 280 B.C.)

* Hipparcus of Nicaea

* Claudius Ptolemy
** Almalgest
** Geographia
** Stereographic projection
** Use of latitude and longitude
** Ptolemy’s theorem

* Rome

* Nichomachus of Gerasa (A.D. 100)

* Cidenas / Kidinnu (330 B.C.)

* Menelaus (c. A.D. 100)

* Heron (c. A.D. 100)

* Diophantus (c. A.D. 250)

G.H.F. Nesselman in Die Algebra der Griechen distinguished between rhetoric algebra, syncopated algebra, and symbolic algebra

* Pappus (c. Early 4th century)
Synagoge
Treasury of Analysis
Analumenos

* Zenodorus

Isoperimetric problems

* Proclus (410 - 485 A.D.)

* Anicius Manlius Severinus Boethius
** Topographia Christiana

* Orestes

* Hypatia

Arithmos vs. Logistics/Computation

* Theodosius I (394) - Byzantine Empire

* Siddhāntās — Sūrya Siddhānta

* Āryabhata

* Liu Hui (A.D. 263)
Nine chapters

* Zu Chongzhi (tsu Ch'ung-Chih) (430 - 501)
Value of Metius

After Alknaar burgomaster
Adriaen Anthoniszoon (c. 1580) whose sons called themselves Metius

* T'ang Dynasty (618-906)
Printing began

Dynasty progression: Han -> T'ang -> Song/Sung -> Yuan
960-1279

1115 - Printed edition of the Nine chapters

* Wang Xiaotong (Wang Hsiao-t'ung) (c. 625)

* Qin Jiushao (Chi'n chiu-shao) (1247)

Theory of indeterminate equations. Solving equations by generalizing the method of succesive approximations popularized by Horner in 1819.

* Brahmagupta (c. 625)

* Mahāvīra (Mysore School) (c. 850)
* Bhāskara (1150)
* Nīlakanta Somayaji (c. 1500)
Kenos - Sūnya

* Sassanian Period (224 - 641)

* Severus Sēbōkt
* Al-Fazārī translated Siddhāntās (773)
* Gobâr numerals


* Al-Mansūr (754-775)
* Hārūn al-Rashīd (786-809)
* Al-Mámūn (813-833)
Promoted Astronomy

* House of Wisdom at Baghdad

* Muhammad ibn Mūsā al-Khwārizmi (f 825)

* Charlemagne (724 – 814)

* Arabic Scholars

Persians, Tadjiks, Egyptians, Jews, Moors

* Al-Battani (Albategnius) (850-929)
Umbra Extensa

* Abū-l-Wafā (al-Būzjanī) (940-997/8)
Sine theorem of spherical trigonometry

* Al-Karki (Al-Karajī)
Worked with surds

* Omar Khayyam (al-Khayyāmi) (c. 1038/48 – 1123/31)
Rubaiyat
Reformed the calendar
** Risala fi'l-barāhīn ’alā masā'il al-jabr wa'l muqābala
Treatise on demonstration of problems of reduction and confrontation

* Nasīr al-dīn at Tūsī (1201-1274)

Tried to prove Euclid’s axiom
John Wallis used his work

* Jemshia Al Kāshī (died 1436)

Horner’s Method

* Al-Uglīdīsī
Decimal Fractions

* Ibn Al-Haitham (Alhazen) (c. 956 - 1039)
Problem of Alhazen

* Abū Kāmil
Influenced Al-Karkhi and Leonardo of Pisa

* Al-Zarqāli (c 1029-1807)
Toledan Planetary tables

* Alfonso and Castile
Alfonsine Tables

* Al-Kāshī of Samarkhand
Decimal fractions

Father Matteo Ricci: Popularized Western Mathematics and Astronomy into China

* Anicius Manlius Severinus Boethius
Died as a martyr of Catholic faith

The Trivium: Grammatica, Rhetorica, Dialectica

Arithmetica, Geometrica, Astronomia, Musica: Quadrivium

* Ecclesiastical Mathematicans

* Alucin
Court of Charlamagne

* Gerbert
French Monk

Became a pope under the name of Sylvester II

* Translators
** Plato of Tivoli
** Gherardo of Cremona
** Robert of Chester

* University of Bologna (1088)

* Mediterranean

* Byzantine

* Adelard of Bath

** Elements Latin Version

* Leonard of Pisa / Fibonacci
Liber Abaci (1202)

Fibonacci Series: Introduced Hindu-Arabic system of numeration into Western Europe

** Practica Geometriae (1220)

* Codex Vigilanus (976)

The adoption of Hindu Arabic numerals were slow. Their introduction met with opposition from public.

Money changers of Florence were forbidden to use them.

Medici account books (1406) has them

From 1439 onward, they replace Roman numerals

Rechenmeister - Reckon Masters / Arithmeticians

In Middle Ages “speculative” mathematics was cultivated among scholastic philosophers who speculated on the nature of motion, of the continumm, and of infinity.

Origen, Aristotle denied the existence of actual infinite

St. Augustine in Civitas Dei accepted the whole sequence of integers as an actual infinity.

Georg Cantor remarked that the transfinitum cannot be more energetically desired and cannot be more perfectly determined and defended than was done by St. Augustine

Thomas Aquinas accepted “infinitum actu non datur” but considered every continuum as potentially divisible ad infinitum.

A continnum as cannot be constituted of indivisibles. A point could generate a line by motion.

Such “speculations” had their influence on the inventors of the infinitesimal calculus in the 17th century and on the philosophers of the transfinite in the 19th: Cavalieri, Tacquet, Bolzano, and Cantor knew the scholastic authors and pondered over the meaning of their ideas.

Thomas Bradwardine investigated star polygons after studying Boethius.

* Nicole Oresme, Bishop of Lisieux in Normandy

Found out that the harmonic series is divergent

** De latitudinibus formarum (c. 1360)
Latitude (Dependent Variable) vs. Longitude (Independent variable)

Rechenhaftigkeit (Sombart) - A willingness to compute, a belief in the usefulness of arithmetic work

* Johannes Müller of Königsberg

* George Peurbach
Teacher of Regiomontanus

* Regiomontanus
** De triangulis omni modis libri quinque (1464, printed 1533)

Euler (1748) normalized trigonometric ratios to radius 1

Classics in this period were considered as “ne plus ultra” (nothing beyond)

* Adam Riese (1492 – 1559)

Introduced Arabic/Indian numerals in Germany

* Scipio del Ferro
General algebraic solution of the cubic equation

* Study of linear perspective
** Brunelleschi
** Donatello
** Uccello
** Masaccio
** Alberti
** Piero della Francesca

First printed mathematical books in Europe: Commercial Arithmetic (Trevisio, 1478)

* Cliques

Scipio del Ferro and team
Cossists
French Algebraists
Port royale

* Luca Pacioli

Remarked that solutions of x^3 + mx = n, x^3  + n = mx seem impossible

** Summa de Arithmetica
Introduced double entry book keeping

** Geometria, Proportioni et Proportionalia (1494)

* Divina Proportione (1509)


General solution of the cubic equation
x^3 + px = q, x^3 = px + q, x^3 + q = px

* Tartaglia
rediscovered the methods of Scipio del Ferro in 1535

* Girolamo Cardano / Jerome Cardan

** Ars Magna (1545)

Ludovico Ferrari defended Cardano in the accusation of making the general solution of the cubic equation public

* Quaesiti of Tartaglia (1546)

* Cartelli of Ferrari (1547-48)

* Rafael Bombelli

** Algebra (1572)
** Geometry (1550)

*** Note on notation used
R[0m.9] = Sqrt(0 - 9)
m stands for minus

Curious that complex numbers appeared in the context of cubic equations and not on quadratic equations which are simpler and the same idea appears in that context too.

* G. J. Rheticus

* Valentin Otho

Trigonometric values for every 10 seconds to 10 places in Opus Palatinum

* Tables of Pitiscus - 15 places

* Adriaen van Roomen
Equation of the 45th degree

* François Viète

First to express π as an infinite product

** In artem analytican isagoge (1591)
First to represent numbers by letters

Cossists: Cosa - Italian for unknown

* Johann Widmann (1489)

First use of + and - in print

* Simon Stevin
Engineer

** La disme (1585)
Introduced decimal fractions

* Johann Kepler

* Thomas Harriot

* Adriaen Vlacq

* Ezechiel de Decker
Assisted by Adriaen Vlacq

* John Napier (or Neper)

** Mir ifici logarithmorum canoni descriptio (1614)

* Henry Briggs

** Arithmetica logarithmica (1624)

Filled the gap between 20,000 and 90, 000 in Briggian logarithms

Natural logarithms appeared contemporaneously with Briggian logarithms, but tehir fundamental importance was not recognized until the infinitesimal calculus was better understood.

* E. Wright
Writer on navigation published some natural logarithms in 1618

* J. Speidell
Also published some natural logarithms in 1619

But after this no tables of logarithms were published until 1770

Mathematics during Renaissance developed due to Rechenhaftigkeit and development of machines in the 17th century.

Heron’s work describes machines.

Machines became popular in renaissance. They lead to the theoretical mechanics and to the scientific study of motion and of change in general.

* Books on machines

* Keyser, early 15th century

* Leon Battista Alberti
Book on architecture (1450)

* Leonardo da Vinci (1500)

* Tartaglia

Nuova Scienzia (1537)
Construction of clocks and orbit of projectiles

* F. Commandino

Translated Archimedes (1558)

Applied the ancient method of integration to compute the centers of gravity.

Finding the centre of gravity was a favorite among Archimedean scholars

* Simon Stevin

Wrote on centers of gravity (1586)
Hydraulics (1586)

* Luca Valeria

Centers of gravity (1605)
Quadrature of parabola (1606)

* Paul Guldin

** Centrobaryca (1641)

Theorem of Guldin on Centroids which was explained by Pappus

In the wake of the scientists in the early 17th century came the work of Kepler, Cavalieri, Torricelli.

Celestial Mechanics / Terrestrial Mechanics

* Johann Kepler

** Nova stereometria doliorum vinariorum (1615)

* Galileo Galilei
Found the parabolic orbits of projectiles

Kinematics of freely falling bodies

Theory of elasticity

** Disorsi e dimostrazioni matematiche intorno a due nuove scienze (1638)

Claimed the cardinality of number of squares to be equal to that of the totality of all numbers (natural numbers?)

The actual infinnite given in the Discorsi was consciously directed against the Aristotelian and scholastic position represented by Simplicio

* Bonaventura Cavalieri

** Geometria indivisibilius continuorum (1635)

Principle of Cavalieri: All solids of same altitude with the same area in every planar cross section at the same height has the same area

* René Descartes

Rojected homogeneity restrictions
An algebraic equation became a relation between numbers

Did a consistent application of the well developed algebra to the geometrical analysis of the ancients

** Géométrie (1637)
Appendix to Discours de la Méthode

* Pierre de Fermat

A lawyer at Toulouse

Discovered maxima and minima by slightly changing the variable in a simple algebraic equation and then letting the change disappear.

Studied Diophantus

** Isagoge (1679)
Printed in 1679, written earlier than Descartes

** Fermat’s theorem
Prime of form 4n + 1 can be expressed once and only once

a^(p-1) - 1 divisible by p when p is prime and a is coprime to p.

Asserted x^2 - Ay^2 = 1 has an unlimited number of integer solutions.

Fermat and Pascal together founded the mathematical theory of probability

* John Wallis
Tractacus de sectionibus conicis (1655)

* Johan De Witt
De Witt and Halley produced Table of annuities

** Elementa curvarum linearum (1659)

* Marquis L’Hospital

** Analyse des infiniment petits (1696)
Rule of L’Hospital

** Traité analytique des sections coniques (1707)

All of these works referenced Apollonius

First to work boldly with algebric equations was Newton in his study of cubic curves.

The problem of finding tangent to a curve started finding a more prominent place.

Followers of Cavilieri: Torricelli, Isaac Barrow.

* Isaac Barrow

Explained integration and differentiation as inverse problems

* Grégoire de Saint-Vincent

Calculated and solved Zeno’s paradox of Achilles and Tortoise, inspired by the spirit of their age and medieval scholastic writings on the nature of the continuum and the latitude of forms.

* [Historian] Bartholomew

* [Historian] Giovanni Villani

* Gilles de Roberval (1602 – 1675)

French Mathematician

* Christopher / Christiaan Huygens

Studied tractrix, the logarithmic curve, the catenary, and established the cycloid as a tautochronus curve.

** De ratiociniis in ludo alea (1657)

Huygens hearing about the correspondence between Fermat and Pascal tried to find his own answers on probability theory. These inquiries resulted in this work

** Horologium Oscillatorium (1673)

** Wave theory of light

** Ring of Saturn

* Olaf Rømer

* Thomas Young

* E.S. Fischer

Elements of Natural Philosophy

* Blaise Pascal

Chevalier de Meré approached Pascal with a aquestion concerning problème des points. This lead to a correspondence with Fermat that resulted in establishing the field of modern probability theory.

Pascal’s theorem at age 16

Lead the life of a Jansenist at Port-Royal

First to establish a satisfying formulation of the principle of complete induction

** Traité des sinus du quart de circle

** Triangulum characteristicum

** Traité général de la roulette (1658)
Published under the name of A. Dettonville

* Isaac Newton (1642–1727)

Had the idea of calculus in 1655-66 but published in 1704-36

Laid the foundation of potential theory
Solved the two body problem for spheres

Laid the beginnings of a theory of the moon's motion
His axiomatic treatment postulated absolute space and absolute time

** Theory of fluxions
** Universal gravitation

** Composition of light

** Study of infinite series through Wallis’ Arithmetica
** Fluxions vs. Fluents
** Method of Fluxions (1736)

** Philosophiae naturalis principia mathematica (1687)
Establishes mechanics on an axiomatic foundation
Contains the law of gravitation

** Enumeratio linearum tertii ordus (1704)
Classification of plane cubic curves into 72 species

** Arithmetica universalis

** Work on series (1699)

** Quadrature of curves (1693; published 1704)

** Opticks (17024)

* Robert Boyle

* Gottfried Wilhelm Leibniz (1646 – 1716)

** Scientia generalis
** Characteristica generalis
Lead to permutations and combinations
Symbolic logic
Proposed the study of isochrone which was carried out by Jakob Bernoulli

** Lingua Universalis
His invention of the calculus must be understood against this philosophical background of his search for a lingua universalis of change and of motion in particular.

** Found calculus between 1673 and 1676

Newton's approach was kinematical, Leibniz’s was geometrical

Leibniz thought in terms of the characteristic triangle.

This had appeared in Pascal and Barrow’s Geometerical lectures of 1670

** Nova methodus pro maximis et minimis, itemque tangentibus, quae nec fractal nec irrationales quantitates, moratur, et singulare pro illis calculi genus
Leibniz’ calculus was first published in 1684

Followed by a paper in 1686 that contained the rules of integral calculus

* Jakob Bernoulli

Studied the logarithmic spiral.
eadem mutata resurgo: Evolute of a logarithmic spiral is itself.

Both the pedal curve and the caustic with respect to the pole.

** Polar coordinates
** Lemiscate (1695)
** Isochrone (1690)
** Isoperimetric figures (1701)
** Ars conjectandi (1713)
Theory of probabilites

** Theorem of Bernoulli
Bernoulli’s numbers appear in the discussion of Pascal’s triangle

Jakob and Johann are considered as inventors of calculus of variations because of their contribution to the problem of brachistochrone.

It is the curve of quickest descent for a mass point moving between two points in a gravitaitonal field.

The soulition of the brachistochrone turned out to be cycloid. They also found the equation of the geodesics on a surface.

The cycloid curve also solves the problem of tautochrone.

* Daniel Bernoulli

Son of Johann Bernoulli

Paradox of St. Petersburg

Was prolific in applying mathematics to other sciences: Astronom, Physics, Physiology, Hydrodynamics

** Hydrodynamica (1736)
Bernoulli’s law on hydraulic pressure
Kinetic theory of gases

* Vibrating String Problem
First introduced by Brook Taylor in 1715. Led to the theory of PDEs.

* Willebrord Snellius (1580 – 1626)
Snell’s law

** Tiphys Batavus (1624)

* James Gregory

Found binomial series

Arrived at Taylor’s series

Found the Leibniz serii

** Exercitationes geometricae (1668)

* Bernard Nieuwentjit
Burgomaster of Purmerend in 1694 criticized Leibniz’ calculus

* George Berkeley
Dean of Derry
Known for extreme idealisim (esse est percipi)
Criticized Newton’s theory of fluxions in The Analyst (1734)

Infinitesimals: Ghost of departed quantities
Caricatured Newton’s work as manifest sophism

* John Landen
** Residual Analysis (1764)
Method which has some affinity to the algebraic method of Lagrange

Descartes work was placed on the index in 1664

Voltaire
Lettres sur les Anglais (1734)
Introduced Newton to the French reading public

Cassini (Jean Dominique)
Cassin’s Oval

** Pierre de Maupertius
Least action as mvs

** Samuel König
Controversy concerning the principle of least action

Euler restated the principle in the form that integral of mvds must be a minimum

* Alexis Claude Clairaut
Recherches sur les courbes à double courbure (1731)
A first attempt to deal with the analytical and differential geometry of space of curves
** Théorie de la figure de la terre (1743)

A standard work on the equilibrium of fluids
** Attraction of ellipsoids of revolution

** Théorie de la lune (1752)
Clairaut’s equation
First known examples of a singular solution

* Denis Diderot
* Jean Le Rond d’Alembert

** Traité de dynamique

Method of reducing the dynamics of solid bodies to statics known as d’Alembert’s principle

Fundamental theorem in algebra is sometimes called d’Alembert’s theorem because of his attempt at proof (1746)

** d’Alembert’s paradox: Paradox in the theorem in the theory of probability

Theory of probability advanced in 18th century by further elaboration of the ideas of Fermat, Pascal, and Huygens

* Abraham de Moivre

** The Doctrine of CHances (1716)

* Edict of Nantes (1685)

* James Stirling

* Georges-Louis Leclerc
Introduced the first example of a geometric probability
Needle problem

Marquis de Condorcet
** Probabilité des judgements

* Colin Maclaurin

** Geometria Organica (1720)
** Cramer’s Paradox
** Treatise of Fluxions (2 volumes) (1742)

** Series of Maclaurin
Did considerations of convergence
Integral test for infinite series

** Brook Taylor

** Introduced the problem of the vibrating string

** Methodus incrementorum (1715)


* Johannes Hudde

Mayor of Amsterdam

Generalized Fermat's results

* Paul Guldin

* André Tacquet
** On Cylinders and Rings (1651) influenced by Pascal

Since there was no periodicals at the time, there were discussion circles and constant correspondence

Latitude of forms

In the writings of Tacquet and Guldin the term “exhaustion” appears for the first time

* Marin Mersenne
Minorite Father

** Mersenne Primes

* Immanuel Kant

* Richard Baltzer

* Eugenio Beltrami

* Voetius

* John Wallis

** Arithmetica Infinitorum (1655)

Used infinity symbol to mean 1/0

Claimed that -1 > Infinity

* Desargues

New interpretation of geometry

Book on perspective (1636)

** Brouillon proet d'une atteinte aux événements des recontres d'un cone avec un plan (1639)
Deals with infinity, involutions and polarities

** Desargues’s theorem on perspective triangles (1648)

* Peter Turner

* Jacobi

* Leonard Euler (1707 – 1783)

From Basel

Described as the most productive mathematician of all time.
Euler’s father trained under Jakob Bernoulli and Euler trained under Johann.

Had the special tutelage of Frederick the Great.

Lost one eye in 1735, and the other eye in 1766, but nothing could interrupt his enormous productivity.

Catenoid and Right helicoid are minimal surfaces

V + F - E = 2 for a closed polyhedron — Was already known to Descartes

The line of Euler in the triangle
Curves of constant width (orbiform curves)
Euler’s constant = 0.5772156…
Limit from n to infinite (1 + 1/2 + … + 1/n - log n)

Law of reciprocity for quadratic residues

** Introductio in analysin infinitorum (1748)

Influenced Lagrange, Laplace, and Gauss

Considered the first book on analytical geomeotry

- Algebraic theory of elimination
- Chapter on the Zeta function and its relation to the prime number theory
- Partitio numerorum
** Institutiones calculi differentialis (1755)
** Institutiones calculi integralis (1768-74)
Three volumes
Has section on differential equation with its distinction between “linear”, “exact”, and “homogeneous” equations

** Mechanica, sive motus scientia analytice exposita (1736)
Newton’s dynamics of the mass point was developed with analytical methods

** Theoria motus corporum solidorum seurigidorum (1765)

** Vollständige Anleitung zur Algebra (1770)

** Methodus inveniendi lineas curvas maximi minimive proprietate gaudentes (1744)

- First exposition of calculus of variations
- Euler’s equations

** Theoria motus planetarium et cometarum (178774)
** Attraction of ellipsoid (1738)
** Dioptrica (1769-71)
3 volumes
Theory of passage of light through a system of lenses

** Letters to a German Princess
Catalogue of most important problems of natural science
Remained a model of popularization

Worked on divergent series which were made rigorous by G. H. Hardy in 1949

** Differential Calculus (1755)

There exist infinite orders of infinitely small quantities which though the all = 0, still have to be well distinguished among themselves, if we look at their mutual relation, which is explained by a geometrical ratio

* Guido Grandi
Studied rosaces (r = sin n theta)

* Notes on Differential Calculus

Newton used the term “prime and ultimate ratio” for the “fluxion”
d'Alembert replaced this notion by the conception of a “limit”
d’Alembert’s conception of infinities of different orders
Secant becomes the tangent when the intersection of two points are one
Does a variable quantity reach its limit? or does it never reach it?

* Joseph-Louis Lagrange (1736 – 1813)

Purely analytical calculus of variations
** Mécanique analytique (1788)

** Particular solution to the three-body problem (1772)

** Sur la résolution des équations numériques

** Réflexions sur la résolution algébrique des équations

Rational functions of the roots and their behaviour under the permutations of the roots.

This influenced Ruffini, Abel, and Galois

Investigated quadratic resudiues

Proved every integer is the sum of four or less than four squares

** Théorie des fonctions analytiques (1797)
** Leçons sur le calcul des fonctions (1801)

Rejected the theory of limits as indicated by Newton and formulated by d’Alembert

Any function can be defined by the Taylor’s series

The derivatives f'(x), f''(x) were defined as the coefficients h, h^2, in the Taylor expansion of f(x+h)

The notation f'(x), f''(x) is due to Lagrange

First built the theory of functions of a real variable
Use of his own calculs of variations made the unification of the varied principles of statistics and dynamics possible

In statistics by the use of the principle of virtual velocities
In dynamics by the use of d’Alembert’s principle

Lagrangian form: d/dt(∂T/∂q_i - ∂T/∂q_i) = F_i

* Lazare Carnot
Organisateur de la victoire
** Réflexions sur la métaphysique du calcul infinitésimal (1881)

* Pierre-Simon Laplace (1749 – 1827)

** Théorie analytique des probabilités (1812)
** Mécanique céleste (5 vols., 1799 – 1825)
** Essai philosophique sur les probabilités (1814)
** Exposition du système du monde (1796)
*** Nebular hypothesis: Independently proposed by Kant in 1755 and before Kant by Swedenborg (1734)

* Carl Friedrich Gauss (1777 – 1855)

* Johann Bolyài

* Abraham Kestner

* Georg Kluegel

* Nikolay Ivanovic Lobachevsky (1792-1856)

* Johann Bartels

* Riemann

* Marin Mersenne

* Johann Heinrich Lambert (1728 – 1777)

* Emergence of Abstract Algebra

Bourbaki identifies three threads that braided together to result in the modern field of abstract algebra.

A nice article on this is here: http://www.math.hawaii.edu/~lee/algebra/history.html

1/ Algebraic theory of numbers
Gauss, Dedekind, Kronecker, and Hilbert

2/ Permutation Groups
Legrende, Abel, and Galois

3/ Linear algebra and hypercomplex systems

* Karl Hermann Amandus Schwarz (1843 – 1921)

* Ernst Kummer

Theory of ideal numbers

* David Hilbert

* Kurt Grelling

* Leonard Nelson
Heterological paradox

* Bertrand Russell

* William Kindgon Clifford

* Adolph Ganot

Author of Einstein’s textbook

* Henri Poincaré

* Felix Klein

* Giuseppe Peano

New axioms for Euclid Geometry

* Alfred North Whitehead

* Charles Peirce

* Fresnel

* Maxwell

* Hendric Anton Lorenz

* Paul Ehrenfest

* G. G. Stokes

* Armand-Hippolyte-Looius Fezeau

* Albert Michealson

* Alexander Graham Bell

* William Thompson

* André Pater

* Edward Williams Morley

* George Francis Fitzgerald

* Heirneich Weber

* Albert Einstein

* Marcel Grossmann

* Robert Brown

* Abraham Pais

* Jean-Baptiste Perrin

* Max Planck

* Max Von Laue

* Hermann Minkowski

* Ernst Mach

* Arnold Sommerfeld

* Philipp Lenard

* Johannes Stark

* Weiner Heisenberg

* Encrico Fermi

* Edwadr Teller

* Victor Weiskopf

* Watther Mayer

* Wolfgang Pauli

* Edward Witten

* John Schawrz

* Erwin Schrödinger

* Max Born

* Pascual Jordan

* Murray Gell-Mann

* Paul Dirac

* John Bell

* Toichiro Kinoshita

* Theodor Kaluza

* Oscar Klein

* Gabriele Venziano

* John Wheeler

* Geoffrey Chew

* Yoichiro Nambu

* Holger Nielsen

* Leonard Susskind

* J. Robert Oppenheimer

* Richard Feynman

* Julian Schwinger

* Sin-itino Tomanga

* Calabi

* Stephen Yau

* Pierre Ramond

* André Neveu

* Joel Scherk

* Michael Green

* Andrew Strominger

* Brian Greene

* Nathan Seinberg

* Stephen Hawiking

* Cumrun Vata

* Alfred Tarski

* Steven Givant

Givant and Tarski worked on relation algebra which was pioneered by Peirce

* Øysten Ore

** [[https://www.jstor.org/stable/1968580][On the Foundation of Abstract Algebra I (1935)]]

* Garrett Birkhoff

** [[http://math.hawaii.edu/~ralph/Classes/619/birkhoff1935.pdf][On the Structure of Abstract Algebras (1935)]]

* Articles

** [[https://www.scientificamerican.com/article/stone-age-mathematics/][Stone Age Mathematics]]
D. J. Struik

** [[https://www.jstor.org/stable/41133224][The Ritual Origin of Geometry]]
A. Seidenberg

** [[https://www.jstor.org/stable/41133226][The Ritual Origin of Counting]]
A. Seidenberg

** [[https://www.jstor.org/stable/41133511][The Origin of Mathematics]]
A. Seidenberg

** Omar Khayyam, Mathematician
D. J. Struik

** The Binomial Theorem: A widespread concept in Medieval Islamic Tradition
C. M. Yadagiri

** Amer. Math. Monthly vol 21 (1914)) Page 37-48

L. C. Karpinski

** The prohibitios of the use of Arabic numerals in Florence
D. J. Struik

** History of the Exponential and Logarithmic Concepts (7 aricles) (1913)
Florian Cajori

** Leibniz, the Master Builder of Mathematical Notations
Florian Cajori

** Indivisibles and ghosts of departed quantities in the history of mathematics
Florian Cajori

** Cardano: The Gambling Scholar
O. Ore

** Development of Number Theory in Europe till the 17th century
G. P. Matvierskaya

** [[https://webspace.science.uu.nl/~hietb101/gnpdf/freudenthal_Huygens_foundations.pdf][Huygen’s Foundation of Probability]]
H. Freudenthal

** The Discover of Logarithms by Napier (1915- 16)
H. S. Carslaw

** Papers on Stevin, Della Faille, Tacquet, De Saint-Vincent
H. Bosmans

** The Development of Trigonometric Methods Down to the close of the 15th century (1921 - 22)
D. J. Bord

** The Story of Reckoning in the Middle Ages (1926)
F. A. Yeldham

** The Sphere of Sacrobosco (1949)
L. Thorndike

** The Science of Mechanics in the Middle Ages
M. Clagett

** Archimedes in the Middle ages, Vol I. (1965)
M. Clagett

** Six Wings: Men of Science of the Renaissance (1957)
G. Sarton

** Sixteenth Century French Arithmetics and the Business Life (1960)
N. Z. Davis

** Rara Arithmetica (1908)
D. E. Smith

* The Role of Scientific Societies in the 17th century
M. Ornstein

** The Italian Renaissance of Mathematics (1975)
P. L. Rose

* Books

** Read

** A Concise History of Mathematics
4 January 2021

A good review of mathematics starting from antiquity till the first half of 20th century. Particularly interesting is the periods between 17th-19th century which has been described in quite good detail given the limited number of pages devoted to each century. Author devotes a few chapters for mathematics from around the world (especially during the early phases), Europe and neigbhourhood regions are given central importance throughout the text.

** [[https://amzn.to/31O4yzi][Euclid’s Window]]
Leonard Mlodinow (2001)

A whirlwind tour of how reconfiguration of Eucild’s axioms lead to the birth of non-Euclidean geometries which figured a prominent role in the 20th and 21st century Physics and how it ended up influencing our understanding of the world. The details of the theoretical portions are presented for the lay person and hence only brief outlines are presented, but the historical trajectory being detailed is rather interesting to follow to understand how work in geometry influenced physical theories.

** Gödel’s Proof
Ernest Nagel and James R. Newman

* Legend

❤️ - Interested in reading

** The Study of the History of Mathematics ❤️
G. Sarton (1936)

It has the classic quote:
#+BEGIN_QUOTE
The ways of discovery must necessarily be very different from the shortest way, indirect and circuitous, with many windings and retreats. It is only at a later stage of knowledge, when a new domain has been sufficiently explored, that it becomes possible to reconstruct the whole theory on a logical basis, and to show how it might have been discovered by an omniscient being, that is, how it might have been discovered if there had been no real need of discovering it!
#+END_QUOTE

** Introduction to the History of Science
G. Sarton

** Bibliography and Research Material of the History of Mathematics
K. O. May (1973)

** Outline of the History of Mathematics
R. C. Archibald

** Work of historial Hofmann J.E on Grégoire de Saint-Vincent, Fermat, Priority struggle b/w Newton and Leibniz, Leibniz, Frans van Schooten den Jüngere

** A History of Mathematics ❤️
A. F. Carjori

** History of Mathematics ❤️
D. E. Smith

** Numbers and Numerals
D. E. Smith and J. Ginsburg

** Code of the Quipos: A Study in Media, Mathematics, and Culture
M. Ascher and D. Ascher

** Men of Mathematics
E. T. Bell

** A History of Mathematics frmo Antiquity to the Beginning of the Ninteenth Century
J. F. Scott

** An Introduction to the History of Mathematics ❤️
H. Eves

** Die Entwicklung der Infinitesimalrechnung I (1949)
O. Toeplitz

** L’ouevre mathématique de G. Desargues (1951)
R. L. Taton

** James Gregory, A Tercentary memorial (1939)
H. W. Turnbull

** Patterns of Mathematical Thought in the Later 17th century
D. T. Whiteside (1961)

** Notions Historiques
Paul Tannery (1903)

** Pascal Mathématicien (1951)
P. Montel

** Differentials, Higher-order differentials, and the derivative in the Leibnizian Calculus (1974)
H. J. M. Bos

** Philsophers at War — The Quarrell Between Newton and Leibniz (1900)
A. R. Hall

** The Land of Stevin and Huygens (1981)
D. J. Struik

** L’oeuvre de Pascal en Géométrie Projective (1962)
R. Taton

** A catalog of Jesuit Mathematicians (1964)
T. E. Mulcrone

** [[https://amzn.to/3reVDCp][The Origins of the Infinitesimal Calculus (1969)]]
M. E. Baron

** The Great Mathematicians
W. H. Turnbull

** History of Mathematical Astronomy in India
D. Pingree

** The History of Mathematics
J.E. Hofmann

** A History of Greek Mathematics Volume I, II ❤️
Thomas Little Heath (1921)

** Greek Mathematical Thought and the Origin of Algebra (1968)
J. Klein

** A History of Mathematics ❤️
Carl B. Boyer

** The History of the Calculus
Carl B. Boyer

** Science, Technology, and Society in the 17th Century
R. K. Merton

** The Social and economic Roots of Newton’s Principia
B. Hessen

** The Mathematical Career of Pierre de Fermat
Michael S. Mahoney

** Christiaan Huygens and the development of science in the 17th century
A. E. Bell

** Mathematical Thought from Ancient to Modern Times ❤️
Morris Kline

** A History of Computing Technology
Michael R. Williams

** Makers of Mathematics
Alfred Hooper

** The Renaissance Rediscovery of the Linear Perspective
S. Y. Edgerton

** A History of Greek Philosophy ❤️
W. K. C Guthrie

** The Great Mathematicians
Herbert Turnbull

** The Nature and Growth of Modern Mathematics ❤️
Edna E. Kramer

** Mathematics in Civilization
H. L. Resnikoff and R. O. Wells Jr.

** The Presocratic Philosophers ❤️
G. S. Kirk and J. E. Raven

** Nature and the Greeks ❤️
Erwin Schrödinger

** Pythagoras, A Life
Peter Gorman

** The History of Miletus
Adelaide Dunham

** Pythagoras
Leslie Ralph

** From Lucy to Language
Donald Johnson and Blake Edgar

** Of Men and Numbers
Jane Muir

** A History of Western Philosophy ❤️
Bertrand Russell

** Mathematical Statistics
John Freund

** Subtle is the Lord
Abraham Pais

** Ideas of Space ❤️
Jeremy Gray

** Euclidean and Non-Euclidean Gemoetries
Marvin Greenberg

** The Outline of History
H. G. Wells

** Chronicle of the World
Jerome Burne

** The Life of Greece ❤️
Will Durant

** Mathematics and the Physical World ❤️
Morris Kline

** Mathematics in Western Culture
Morris Kline

** The Mapmakers ❤️
John Noble Wilford

** Hypatia of Alexandria
Maria Dzielksa

** The Decline and Fall of the Roman Empire ❤️
Edward Gibbon

** Science in the Middle Ages ❤️
David Lindberg

** Advanced Algebra and Calculus Made Simple
William Gondin

** Maps and Civilization
Norman Thrower

** Three lectures on Fermat's Last Theorem

L. J. Mordell

** Fermat’s Lats Theorem
H. M. Edwards

** Longitude
Dava Sobel

** The Middle Ages ❤️
Morris Bishop

** The Medieval Machine ❤️
Jean Gimpel

** Intellectuals in the Middle Ages ❤️
Lacques Le Goff

** Introduction to Fourier Analysis and Generalised Functions ❤️
M. J. Lighthill

** Studies in Medieval Physics and Mathematics ❤️
Marshall Clagett

** Studies in Medieval Philosophy ❤️
Stephano Caroti

** The Beginnings of Western Science
David C. Lindberg

** The Dictionary of Scientific Biography
Charles Gillespie

** René Descartes
Jack Vrooman

** Makers of Mathematics
Staurt Hollingdale

** Men and Discoveries in Mathematics
Bryan Morgan

** Mathematics and the Medieval Ancestry of Physics
Geroge Molland

** Episodes in the Mathematics of Medieveal Islam
J. L. Berggren

** Carl Friedrich Gauss: Titan of Science
G. Waldo Dunnington

** Introduction to Mathematical Philosophy ❤️
Bertrand Russell

** Concepts of Space ❤️
Max Jammer

** The Science of Mechanics
Ernst Mach

** Leonhard Euler, Supreme Geometer
C. Truesdell

** Biographien Bedeutender Mathematicker
Heinz Junge

** Riemann, Topology, and Physics ❤️
Micheal Monastrysky

** The Master of Light: A Biography of Albert A. Michelson
Dorothy Michelson Livingston

** Albert Abraham Michelson: The Man and the Man of science
Harvey B. Lemon

** Ulysses S. Grant: Triumph over Adversity 1822 - 1865
Brooks D. Simpson

** The Physicists
Daniel Keves

** Eléments de Physique
Adolphe Ganot

** The Ethereal Aether ❤️
Loyd S. Sowenson

** H. A. Lorentz
G. L. De Haas Lorentz

** Nothingness: The Science of Empty Space
Henning Genz

** Elements of Natural Philosophy ❤️
E. S. Fische

** The Life of James Clerk Maxwell
Louis Campbell and William Garnell

** The Demon in the Aether ❤️
Martin Goldman

** Einstein, A Life
Dennis Brian

** Nineteenth Century Aether Theories ❤️
Kenneth F. Schaffner

** La Science et Hypothèse ❤️❤️
Henri Poincaré

** Einstein: The Life and Times
Ronard Clark

** The Principle of Relativity ❤️
A. Somerfeld

** Relativity
Albert Einstein

** Gravitation ❤️
Charles Misner, Kip Thorne, and John Wheeler

** Einstein, Hilbert, and the Theory of Gravitation ❤️
Jagdish Mishra

** The Feynman Lectures on Physics ❤️
Riychrad Feynman and Matthew Sands

** The Attraction of Gravitation ❤️
John Earman, Micheal Tanssen and John Norton

** New Tactic in Physics: Hiding the Answer
James Glanz

** Knot Physics ❤️
Ivars Peerson

** Jordan, Pauli, Politics, Brecht, and a variable gravitational constant
Engelbert L. Schucking

** A Life of Erwin Schrödinger
Wilter Moore

** Writing the Story of Alphabets and Scripts ❤️
George Jean

** The Quotable Einstein
Alice Calaprice

** Strange Beauty ❤️
George Johnson

** Introduction to Superstrings and M-Theory
Michio Kaku

** The Key to the Universe ❤️
Nigel Calder

** Introduction to the Physics and Psychophysics of Music
Juan Roederer

** Nuclear Physics B258
P. Calendas

** How Faith in the Fringe Paid off for One Scientist ❤️
K. C. Cole

** The Quest for a Theory of Everything Hits Some Snags
Faye Flam

** Explaining Everything ❤️
Madhusree Mukerjee

** Physicist Edward Witten, on the trail of universal truth
Alice Steinbach

** Portrait: Is This the Cleverest Man in the World?
Jack Claff

** Isaac Newton – A biography (1934)
L. T. More

** The Theory Formerly Known as Strings
Michael Duff

** Universe’s Blueprint Doesn’t Come Easily
Douglas M. Birch

** Unfinished Symphony
J. Maddine Nash

** The Elegant Universe ❤️
Brian Greene

** Hunting for Higher Dimensions
P. Weiss

** Beyond Gauge Theories ❤️
John Schwarz (hep-th / 9807195)

* Books by Subject

* Math History Books

** General

*** [[https://amzn.to/2WJvQUW][Conceptual Roots of Mathematics]]
J.R.Lucas (October, 1999)

A pretty good book that discusses the philosophical issues in Mathematics. Starts with the idea of Platonic reality and pitts it against the rival theories of truth. An engaging read that draws upon the author’s wealth of knowledge in mathematics.

*** [[https://amzn.to/2YNBEj2][Plato's Ghost: The Modernist Transformation of Mathematics]]
Jeremy Gray (January, 2008)

*** [[https://amzn.to/2Lhdplu][The Nature and Growth of Modern Mathematics]]
Edna Ernestine Kramer (1981)

*** [[https://amzn.to/2LfbbD5][Foundations and Fundamental Concepts of Mathematics]]
Howard Eves (May 20, 1997)

*** [[https://amzn.to/3g4uttd][Mathematical Thought from Ancient to Modern Times]]
Morris Kline (September 29th, 1972)

*** [[https://amzn.to/2XoWvYO][A Concise History of Mathematics]]
Dirk Struik (1948)

*** History of Mathematics: An Introduction
Viktor Katz

*** The History of Mathematics
David Burton

*** An Introduction to the History of Mathematics
Howard Eves

*** Foundations and Fundamental Concepts of Mathematics
Howard Eves

*** Bibliography nad Research Material of the History of Mathematics (1973)

*** Exact Sciences in Antiquity
O. Neugebauer
There is also The Exact Sciences in Antiquity (1952) by the same author, both of which are recommended by Dirk Struik.

*** The Bequest of the Greeks (1955)
T. Dantzig

*** The Early History of the Astrolabe
O. Neugebauer

*** Zero: The Symbol, the Concept, the Number
C. B. Boyer

*** The Origin of the Ghubār numerals
S. Gandz

*** The Sources of Al-Khwārizmi’s Algebra
S. Gandz

** Arithmetic
*** [[https://amzn.to/2ZMgKRM][Frege, Dedekind, and Peano on the Foundations of Arithmetic]]
Donald Gilles (1982)

** Algebra

*** [[amzn.to/2WikJDx][Modern Algebra and the Rise of Mathematical Structures]]
Leo Corry (February 28, 1996)

*** [[https://amzn.to/3fAZMLO][A History of Abstract Algebra]]
Israel Kleener (January 1, 2007)

** Logic

*** [[https://amzn.to/2zrwMp2][Honor’s Class]]
Ben Yandell (December 12, 2001)

*** [[https://amzn.to/2zr7UOa][Gnomes in the Fog: The Reception of Brouwer's Intuitionism in the 1920s]]
Dennis E. Hesseling (May 27, 2003)

*** Engines of Logic
Martin Davis (2000)

** Number Theory

*** The Number Concept
L. Conant

*** [[https://amzn.to/3bi0lXt][The Queen of Mathematics: A Historically Motivated Guide to Number Theory]]
Jay R. Goldman (November 15, 1997)

*** [[https://amzn.to/2TeZmkI][Number: The Language of Science]]
Tobias Dantzig (1930)

*** [[https://amzn.to/38ILntR][Number Theory And Its History]]
Øysten Ore (1948)

*** [[https://amzn.to/2ThDDst][To Infinity and Beyond]]
Eli Maor, (January 28, 1986)

*** [[https://amzn.to/2WDGk9G][e: The Story of a Number]]
Eli Maor, (January 1, 1993)

*** [[https://amzn.to/3bGEKs7][The Universal History of Numbers: From Prehistory to the Invention of the Computer]]
Georges Ifrah, 1981

** Analysis

*** [[https://amzn.to/35NzYrl][A History of Numerical Analysis from the 16th through the 19th Century]]
H. H. Goldstine (August 17, 1976)

*** [[https://amzn.to/2M0K2Ep][Analysis By Its History]]

A book that teaches analytics by the way it historically evolved.

** Geometry

*** [[https://amzn.to/2B8pUxT][Geometry By Its History]]

Teaches Geometry by the way it historically unfolded

** Vector Algebra

*** [[https://en.wikipedia.org/wiki/A_History_of_Vector_Analysis][A History of Vector Analysis]]
Michael J. Crowe (1967)

** Set Theory

*** [[https://amzn.to/2YQm8Dg][Labyrinth of Thought: A History of Set Theory and Its Role in Modern Mathematics]]
Jose Ferreiros, Erwin Hiebert, Eberhard Knobloch, Erhard Scholz (November 23, 1999)

** Group Theory

*** [[https://amzn.to/2WG3zyT][The Genesis of the Abstract Group Concept]]
Hans Wussing, (May 16, 1984) (1969?)

*** [[https://amzn.to/3ckAsaL][Symmetry and the Monster: One of the greatest quests of mathematics]]
Mark Ronan, (May 18th, 2006)

** Category Theory

*** [[https://amzn.to/3bl6ceu][From a Geometrical Point of View]]
Jean-Pierre Marquis, (January 1, 2008)

*** [[https://amzn.to/2SU8wmC][Tool and Object: A History and Philosophy of Category Theory]]
Ralph Krömer, (February 16th, 2007)

** Game Theory

*** [[https://amzn.to/3dxcY2t][Von Neumann, Morgenstern, and the Creation of Game Theory: From Chess to Social Science]]
Robert Leonard, (June 1, 2010)

** People

*** Paul Erdos

**** [[https://amzn.to/2Lcz2mQ][My Brain is Open: The Mathematical Journeys of Paul Erdös]]
Bruce Schechter, (September 1, 1998)

*** Hilbert

**** Biography by Constance Reid

*** Euler
**** Leonard Euler by Ronald Calinger
